language: cpp
compiler: gcc
sudo: required

dist: xenial

before_install:
  # C++17
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  # C++17
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - sudo apt-get install -qq autoconf
  - sudo apt-get install -qq libgtkmm-2.4-dev
  - sudo apt-get install -qq libgconfmm-2.6-dev
  - sudo apt-get install -qq libgtkglextmm-x11-1.2-dev
  - sudo apt-get install -qq libasound2-dev
  - sudo apt-get install -qq cmake

script:
  - cmake .
  - make -j4



